Feature/#44 test coverage
maykinmedia/sharing-configs pull request #54
Opened 2022-06-03 09:36 UTC by frekkenSnork

Fixes [#44] 
Checking mock params and adding few tests for the full test coverage

2022-06-08 11:05 UTC, annashamray requested changes
I didn't find the following tests. Could you specify their paths?
*  export form folder field has expected choices 

In the future could you please structure your test functions in this fashion - https://github.com/octoenergy/conventions/blob/master/python.md#unit-test-method-structure 
Adding new lines between arranging, action and assertion blocks will significantly improve readability.

Also for the future testing of django views you may find `django-webtest` really useful. It helps to reduce a lot of boilerplate in testing

2022-06-08 12:45 UTC, frekkenSnork commented on testapp/admin.py
> +        """current state: return list"""
Changed

2022-06-08 12:45 UTC, frekkenSnork commented on tests/test_mock_export.py
> +    def test_button_export_presensce(self):
Corrected

2022-06-08 14:00 UTC, frekkenSnork commented on sharing_configs/client_util.py
> +                resp.raise_for_status()
Done

2022-06-09 09:46 UTC, frekkenSnork commented on sharing_configs/client_util.py
> +            raise ApiException(f"No files available. {exc}")
Made all exceptions a string without a trace-back but left it in except block as an alias "exc" (for example in case of logging in the future)

2022-06-14 10:24 UTC, annashamray commented on .gitignore
> +testapp.migrations
why do you exclude testsapp migrations now?

2022-06-14 10:24 UTC, annashamray commented on tests/test_mock_export.py
> +        print("err ", err_msg)
please remove `print`

2022-06-14 16:04 UTC, joeribekker commented
@frekkenSnork still needs that print statement removed!

2022-06-15 07:25 UTC, joeribekker approved these changes

2022-06-15 07:26 UTC, merged